### ISSUE TITLE
Ability to delete attachments in chat

### ISSUE THREAD

**Issue by NickThackray** [ConnectNowUK/hedgehog-css#4]
When testing I attached the wrong file (PDF) to the chat and then realised there was no way for me to remove it again.

Priority: Low

**Comment by mwargan** [comment]
Hey @NickThackray, closing this for a few reasons. First, it doesn't have much to do with Hedgehog, our design system and language. This is more for our API and our frontend.

Secondly, we haven't planned to allow deleting of posts, because doing so would allow you to manipulate the history of a conversation, change its meaning, and create havoc. This is also why systems like WhatsApp or Messenger don't allow you to delete messages (once they've been seen by at least one other person - the seen-by is another can of worms that we haven't looked at just yet ;)).
